#!/usr/bin/env bash
# Map Intel discrete GPUs to ZE_AFFINITY_MASK, skipping the integrated
# GPU typically at PCI 00:02.0. This helper is only for the optional Intel
# XPU compose stack — NVIDIA/AMD users should not run it.
#
# ZE_AFFINITY_MASK is the *host* Level Zero index list (skips an iGPU hole).
# Do NOT pass it into the vLLM container — intel/llm-scaler-vllm only enumerates
# discrete XPUs as 0,1. DOCKER_ZE_AFFINITY_MASK is that compact list; compose.yml
# must not inject either variable into the service environment.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-"$ROOT/.env"}"

# Known integrated GPU PCI IDs (Arrow Lake, Meteor Lake, Lunar Lake, Raptor Lake).
IGPU_DEVIDS="7d67 7d45 7d55 7d51 a7a0 a7a8 64a0 46a6 46a8 9a49 7dd5 6420"
is_igpu_devid() {
  local id="${1,,}"
  id="${id#0x}"
  for x in $IGPU_DEVIDS; do
    [[ "$id" == "$x" ]] && return 0
  done
  return 1
}

echo "late-gpu: scanning /sys/class/drm/card*" >&2

ze_index=0
mask_parts=()
found_discrete=0

for card in /sys/class/drm/card[0-9]*; do
  [[ -e "$card/device/vendor" ]] || continue
  base="$(basename "$card")"
  # Skip render/control nodes (card0-renderD128, card0-HDMI-A-1, …).
  [[ "$base" =~ ^card[0-9]+$ ]] || continue

  vendor="$(tr '[:upper:]' '[:lower:]' < "$card/device/vendor")"
  [[ "$vendor" == "0x8086" ]] || continue

  device="$(tr '[:upper:]' '[:lower:]' < "$card/device/device")"
  pci="$(basename "$(realpath "$card/device")")"
  devid="${device#0x}"

  igpu=0
  if [[ "$pci" =~ :00:02\.0$ ]]; then
    igpu=1
  elif is_igpu_devid "$devid"; then
    igpu=1
  fi

  role="discrete"
  [[ "$igpu" -eq 1 ]] && role="igpu"

  echo "late-gpu: $base pci=$pci device=$device role=$role ze_index=$ze_index" >&2

  if [[ "$igpu" -eq 0 ]]; then
    mask_parts+=("$ze_index")
    found_discrete=1
  fi
  ze_index=$((ze_index + 1))
done

if [[ "$found_discrete" -eq 0 ]]; then
  echo "late-gpu: WARNING no discrete Intel GPU found; leaving ZE_AFFINITY_MASK empty" >&2
  MASK=""
else
  MASK="$(IFS=,; echo "${mask_parts[*]}")"
fi

VIDEO_GID="$(getent group video 2>/dev/null | cut -d: -f3 || true)"
RENDER_GID="$(getent group render 2>/dev/null | cut -d: -f3 || true)"
[[ -n "$VIDEO_GID" ]] || VIDEO_GID=44
[[ -n "$RENDER_GID" ]] || RENDER_GID="$VIDEO_GID"

KEEP="$(mktemp)"
if [[ -f "$OUT" ]]; then
  # Preserve MODEL_PATH / image / TP / etc. Only rewrite GPU + GID lines.
  grep -vE '^(# Generated by docker/detect-gpus|# Generated —|ZE_AFFINITY_MASK=|DOCKER_ZE_AFFINITY_MASK=|VIDEO_GID=|RENDER_GID=)' "$OUT" \
    | grep -v '^$' > "$KEEP" || true
fi
# Compact 0..N-1 for the container: intel/llm-scaler-vllm only lists discrete XPUs.
# Recorded for operators; compose.yml does not pass this (or ZE_AFFINITY_MASK) in.
DOCKER_MASK=""
if [[ "$found_discrete" -eq 1 ]]; then
  n=0
  docker_parts=()
  for _ in "${mask_parts[@]}"; do
    docker_parts+=("$n")
    n=$((n + 1))
  done
  DOCKER_MASK="$(IFS=,; echo "${docker_parts[*]}")"
fi
{
  echo "# Generated by docker/detect-gpus.sh — GPU/GID lines are rewritten; other keys are kept"
  echo "ZE_AFFINITY_MASK=${MASK}"
  echo "DOCKER_ZE_AFFINITY_MASK=${DOCKER_MASK}"
  echo "VIDEO_GID=${VIDEO_GID}"
  echo "RENDER_GID=${RENDER_GID}"
  cat "$KEEP"
} > "$OUT"
rm -f "$KEEP"

GIDS_YML="$(dirname "$OUT")/compose.gids.yml"
{
  echo "# Generated — unique host GIDs only (Docker rejects duplicates)"
  echo "services:"
  echo "  vllm:"
  echo "    group_add:"
  echo "      - \"${VIDEO_GID}\""
  if [[ "$RENDER_GID" != "$VIDEO_GID" ]]; then
    echo "      - \"${RENDER_GID}\""
  fi
} > "$GIDS_YML"

echo "late-gpu: wrote $OUT" >&2
echo "ZE_AFFINITY_MASK=${MASK}"
echo "late-gpu: typical dual discrete + iGPU => 1,2" >&2
echo "late-gpu: if Level Zero enumerates only discrete cards => 0,1" >&2
